apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: handelnine-apps
spec:
  generators:
  - matrix:
      generators:
      - clusters:  # Cluster generator: Selects only the specific cluster by its unique label
          selector:
            matchLabels:
              brand: bg  # Match the cluster's unique label
              deploy-apps: true  # Match the cluster's unique label
      - list:  # List generator: Defines the 5 stores for this brand
          elements:
          - app: nginx-blue-green-app
            namespace: argo-bg-test
      - list:  # List generator: Defines the 5 stores for this brand
          elements:
          - store: blue
          - store: green
  template:
    metadata:
      name: '{{.brand}}-{{.app}}'  # Generates names like your-app-brand1-store1
    spec:
      project: default
      source:
        repoURL: https://github.com/your-repo/helm-chart.git
        targetRevision: HEAD
        path: apps/{{.app}}
        helm:
          valueFiles:
          - values_bg.yaml
          - values_{{.brand}}_{{.store}}.yaml  # Brand-specific values file
      destination:
        server: '{{.server}}'  # From the Cluster generator (the matched cluster)
        namespace: {{.namespace}}  # Customize as needed

