apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-nginx-xyz
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:  # Cluster generator: Selects only the specific cluster by its unique label
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
          brand: "qa"  # Match the cluster's unique label in the cluster secret resource
          deploy-apps: "true"  # Match the cluster's unique label in the cluster secret resource
      values:
        app: backend
        brand: ninetribe
        namespace: default
  template:
    metadata:
      name: my-nginx  # Generates names like your-app-brand1-store1
    spec:
      project: default
      source:
        repoURL: https://github.com/burhanshaikh/argo-bg-test.git
        targetRevision: main
        path: nginx/test-nginx
        helm:
          releaseName: tourbillon
          valueFiles:
          - values.yaml
      destination:
        server: '{{.server}}'  # From the Cluster generator (the matched cluster)
        namespace: '{{.values.namespace}}'  # Customize as needed
      syncPolicy:
        automated: {}
